DROP TABLE IF EXISTS orders;
CREATE TABLE IF NOT EXISTS orders

(id INT PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(45) NOT NULL,
Manufactorer VARCHAR(45) NOT NULL,
year YEAR NOT NULL,
count INT,
storyline TEXT
);